name: pypi deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Instala nix single user
      run: |
        BASE_URL='https://raw.githubusercontent.com/ES-Nix/get-nix/' \
        && SHA256=87fa0f1dbfdd28a1f99b39d5bd4dcc39de97bc64 \
        && NIX_RELEASE_VERSION='2.10.2' \
        && curl -fsSL "${BASE_URL}""$SHA256"/get-nix.sh | sh -s -- ${NIX_RELEASE_VERSION} \
        && . "$HOME"/.nix-profile/etc/profile.d/nix.sh \
        && . ~/."$(basename $SHELL)"rc \
        && export TMPDIR=/tmp \
        && nix flake --version \
        && nix registry pin nixpkgs github:NixOS/nixpkgs/ea4c80b39be4c09702b0cb3b42eab59e2ba4f24b
        echo "$HOME"/.nix-profile/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        nix develop .# --command sh -c 'make poetry.install'

    - name: build package
      run: |
        nix develop .# --command sh -c 'source .venv/bin/activate && make package.build'

    - name: deploy package
      env:
        PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: make package.publish PASSWORD=$PASSWORD
